version: 2
jobs:
  build:
    docker:
      - image: nixos/nix
    steps:
      - checkout
      - run:
          name: Download nix channels
          command: "nix-channel --add https://nixos.org/channels/nixos-21.05 nixpkgs && nix-channel --update"
      - run:
          name: Resolve/Update Dependencies
          command: "nix-build release.nix"
      - run: "./result/bin/site build"
      - run:
          name: Deploy
          command: "nix-shell -p netlify-cli --run 'netlify deploy --dir _site --prod'"

workflows:
  version: 2
  build:
    jobs:
      - build
