version: 2
jobs:
  build:
    docker:
      - image: nixos/nix
    steps:
      - checkout
      - run:
          name: Download nix channels
          command: "nix-channel --add https://nixos.org/channels/nixos-21.05 nixpkgs && nix-channel --update"
      - restore_cache:
          name: Restore cached nix store
          keys:
            - dependencies-{{ checksum "default.nix" }}
      - run:
          name: Resolve/Update Dependencies
          command: "nix-build default.nix"
      - run: "./result/bin/site build"
      - run:
          name: Deploy
          command: "nix-shell ./default.nix --run 'netlify deploy --dir _site --prod'"
      - save_cache:
          name: Cache dependencies
          key: dependencies-{{ checksum "default.nix" }}
          paths:
            - "/nix/store"
workflows:
  version: 2
  build:
    jobs:
      - build
